website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from .forms import ProjectForm
from .models import *
from . import db
from textblob import TextBlob
import pandas as pd
import json
import io

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def user_home():
    return render_template("user_home.html", user=current_user)

@views.route('/create-project', methods=['GET', 'POST'])
@login_required
def project_form():
    form = ProjectForm()
    return render_template('create_project.html', user=current_user, form=form, review_csv='')

@views.route('/delete-project', methods=['POST'])
def delete_project():
    project = json.loads(request.data)
    projId = project['projId']
    project = Project.query.get(projId)
    if project:
        if project.user_id==current_user.id:
            db.session.delete(project)
            db.session.commit()
    return jsonify({})

@views.route('/analyze-sentiment', methods=['GET', 'POST'])
@login_required
def analyze_sentiment():
    form = ProjectForm()
    if request.method == 'POST':
        csv_data = request.files['csv_data']
        if csv_data:
            csv_data = csv_data.read().decode('utf-8', errors='replace')
            csv_stream = io.StringIO(csv_data)
            output_df = analyze_sentiment(csv_stream)
            return render_template('display_sentiment.html', output=output_df, user=current_user, form=form, csv_data=output_df.to_csv(index=False))
    else:
        flash('POST not successful', category='error')
        return render_template('create_project.html', user=current_user)
    
@views.route('/save-sentiment', methods=['POST'])
@login_required
def save_sentiment():
    form = ProjectForm()
    title = request.form.get('title') 
    desc = request.form.get('desc')
    data = request.form.get('sentiment_data')
    if data:
        new_project = Project(title=title, desc=desc, csv_data=data, user_id=current_user.id)
        db.session.add(new_project)
        db.session.commit()
        flash('Sentiment data saved to the database!', category='success')
        url = url_for('views.project_view', project_id = new_project.id)
        return redirect(url)
    else:
        flash('Data is missing or empty. Sentiment data not saved.', category='error')

    return render_template('display_sentiment.html', user=current_user, form=form)

@views.route('/project-view/<int:project_id>')
@login_required
def project_view(project_id):
    project = Project.query.get(project_id)
    csv_data = project.csv_data
    n = len(csv_data)
    csv_data[:n-2]
    csv_stream = io.StringIO(csv_data)
    output_df = analyze_sentiment(csv_stream)
    return render_template('view_project.html', project=project, output = output_df, user=current_user)

def analyze_sentiment(csv_data):
    df = pd.read_csv(csv_data)
    polarity_scores = []
    subjectivity_scores = []
    for index, row in df.iterrows():
        review = row['Review']
        analysis = TextBlob(review)
        polarity = analysis.sentiment.polarity
        subjectivity = analysis.sentiment.subjectivity

        polarity_scores.append(polarity)
        subjectivity_scores.append(subjectivity)
    def scoreAnalysis(x):
        if x<0:
            return 'Negative'
        elif x>0:
            return 'Positive'
        else:
            return 'Neutral'
    df['Polarity'] = polarity_scores
    df['Subjectivity'] = subjectivity_scores
    df['Sentiment'] = df['Polarity'].apply(scoreAnalysis)
    return df


website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="../static/styles.css">
    
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.2/dist/flatly/bootstrap.min.css"
    />
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body class="d-flex flex-column min-vh-100">

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Admin Login</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form method="POST" action="/admin/admin-login">
              <div class="form-group">
                  <label for="admin_key">Admin Key:</label>
                  <input type="text" class="form-control" id="admin_key" name="admin_key" placeholder="Enter admin key">
              </div>
              <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
              </div>
              <br>
              <button type="submit" class="btn btn-success">Login</button>
          </form>
          </div>
        </div>
      </div>
    </div>

    <nav class="navbar navbar-expand-lg bg-primary px-2" data-bs-theme="dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="navbar-brand" href="#">SentiVue</a>
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          <a class="nav-item nav-link text-white" id="admin" data-toggle="modal" data-target="#exampleModal">Admin</a>
          {% endif %}
        </div>
      </div>
    </nav>


    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div> 

    <footer class="footer text-center text-white bg-primary mt-auto p-2">Created by Atryee Dhar</footer>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
<script type="text/javascript">
    function deleteProject(projId) {
    fetch("/delete-project", {
    method: "POST",
    body: JSON.stringify({ projId: projId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  </body>
</html>

website/templates/create_project.html
{% extends "base.html" %}{% block title %}Create-Project{% endblock %}
{% block content %} 
<h1>Create New Project</h1>
<p class="text-muted">Note: Ensure that the csv file contains fields 'Product' and 'Review', both of type string.</p>
    <form method="POST" action="/analyze-sentiment" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <label for="csv_data"><b>Upload CSV:</b></label>
        <br>
        <input type="file" id="csv_data" name="csv_data" accept=".csv" required><br><br>
        <input class="btn btn-success" type="submit" value="Create Project">
    </form>
<br>
<div id="csvDataPreview">
    <p class="text-muted"><em>A preview of your file will be shown here:</em></p>
</div>

    <script>
        // Function to show CSV data preview
        function showCSVPreview() {
            var fileInput = document.getElementById("csv_data");
            var csvDataPreview = document.getElementById("csvDataPreview");
    
            if (fileInput.files.length === 0) {
                alert("Please select a CSV file first.");
                csvDataPreview.style.display = "none"; 
            } else {
                var file = fileInput.files[0];
                var reader = new FileReader();
    
                reader.onload = function (e) {
                    var csvData = e.target.result;
                    var lines = csvData.split("\n");
                    var tableHtml = '<p class="text-muted"><em>preview:</em></p><table class="table table-sm">';
                    for (var i = 0; i < lines.length; i++) {
                    var line = lines[i];
                    var firstCommaIndex = line.indexOf(",");
                    var product = line.substring(0, firstCommaIndex);
                    var review = line.substring(firstCommaIndex + 1);
                        
                    tableHtml += "<tr>";
                    tableHtml += "<td>" + product + "</td>";
                    tableHtml += "<td>" + review + "</td>";
                    tableHtml += "</tr>";
                    }
                    tableHtml += "</table>";
                    csvDataPreview.innerHTML = tableHtml;
                    csvDataPreview.style.display = "block"; 
                };
    
                reader.readAsText(file);
            }
        }

        document.getElementById("csv_data").addEventListener("change", showCSVPreview);
    </script>
{% endblock %}

website/templates/display_sentiment.html
{% extends "base.html" %}{% block title %}Sentiment Analysis{% endblock %}
{% block content %}
    <div class="card card-new-shadow rounded my-2">
    <div class="card-body p-4">
    <h1>Sentiment Analysis Results</h1>
    <form method="POST" action="{{ url_for('views.save_sentiment') }}" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <label for="title">Project Title:</label>
        <input type="text" id="title" name="title" class="form-control" required><br>
        <label for="desc">Project Description:</label>
        <textarea name = "desc" id="desc" class="form-control"></textarea>
        <br>
        <div class="result">
        {{ output.to_html(classes=["table table-hover table-sm text-right"])|safe }}
        </div>
        <br>
        <input type="hidden" name="sentiment_data" value="{{ csv_data }}">
    <div class="result">
        <canvas id="polarity-chart" width="360" height="180"></canvas>
        <br>
        <canvas id="sentiment-chart" width="360" height="180"></canvas>
        <br>
        
        <!--ALL REQUIRED JS CODE-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
        <script>
            var opData = {{ output.to_json(orient='records')|safe}}
            var sentimentData = {{ output[['Product', 'Sentiment']].to_dict(orient='records')|tojson|safe }};
            var scatterplotData = [];
            var sentimentCounts={};
            var reviewLabel = ['1','2','3','4','5','6','7','8','9','10'];
            opData.forEach(function(row) {
            scatterplotData.push({ x: row.Polarity, y: row.Subjectivity });
            });
            sentimentData.forEach(function (entry) {
            var product = entry['Product'];
            var sentiment = entry['Sentiment'];
    
            if (!sentimentCounts[product]) {
                sentimentCounts[product] = {};
            }
    
            if (!sentimentCounts[product][sentiment]) {
                sentimentCounts[product][sentiment] = 0;
            }
    
            sentimentCounts[product][sentiment]++;
            });
    
            var productNames = Object.keys(sentimentCounts);
            var positiveCounts = productNames.map(function (product) {
                return sentimentCounts[product]['Positive'] || 0;
            });
            var negativeCounts = productNames.map(function (product) {
                return sentimentCounts[product]['Negative'] || 0;
            });
            var neutralCounts = productNames.map(function (product) {
                return sentimentCounts[product]['Neutral'] || 0;
            });
    
            function createScatter(chartId, data, labels) {
                var ctx = document.getElementById(chartId).getContext('2d');
                new Chart(ctx, {
                    type: 'scatter',
                    labels: labels,
                    data: {
                        datasets: [{
                            data: data,
                            pointBackgroundColor: 'rgba(0,0,255,1)',
                            pointRadius: 5,
                        }]
                    },
                    options: {
                        legend: {
                            display: false,
                        },
                        title: {
                            display: true,
                            text: "Polarity vs Subjectivity",
                            fontSize: 20,
                        },
                        scales: {
                        xAxes: [{ticks: {min: -1, max:1}}],
                        yAxes: [{ticks: {min: 0, max:1}}],
                        },
                        tooltips: {
                        callbacks: {
                        label: function(tooltipItem, data) {
                            var label = data.datasets[tooltipItem.datasetIndex].label || '';
                            if (label) {
                            label += ': ';
                            }
                            label += 'Review:' + tooltipItem.index + ', Polarity:' + tooltipItem.xLabel + ', Subjectivity:' + tooltipItem.yLabel;
                            return label; 
                            }}
                        }
                    }
                });
            }
            
            var ct = document.getElementById('sentiment-chart').getContext('2d');
            var sentimentChart = new Chart(ct, {
                type: 'bar',
                data: {
                    labels: productNames,
                    datasets: [
                        {
                            label: 'Positive',
                            data: positiveCounts,
                            backgroundColor: 'green',
                        },
                        {
                            label: 'Negative',
                            data: negativeCounts,
                            backgroundColor: 'red',
                        },
                        {
                            label: 'Neutral',
                            data: neutralCounts,
                            backgroundColor: 'gray',
                        },
                    ],
                },
                options: {
                    title: {
                        display: true,
                        text: "Sentiment Counts per Product",
                        fontSize: 20,
                    },
                    scales: {
                        yAxes: [
                        {scaleLabel: {display: true, labelString: "Review Count"}},
                        {ticks: {stepSize: 1}}
                    ],
                    },
                },
            });
    
            createScatter('polarity-chart', scatterplotData, reviewLabel);
            //createHistogram('subjectivity-chart', subjectivityData, ReviewLabel, 'Subjectivity');
        </script>
        </div>
        <button type="submit" class="btn btn-success">Save Project</button>
    </form>
    </div>
    </div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}{% block title %}login{% endblock %}
{% block content %} 

<div class="card card-new-shadow my-3 mx-auto rounded">
    <div class="row no-gutters">
      <div class="col-md-5">
        <img src="../static/login.jpg" class="img-fluid rounded-left">
      </div>
      <div class="col-md-6">
        <div class="card-body px-4 mx-auto">
            <form method="POST">
                <h3 class="text-center card-title">Login</h3>
                <h5 class="text-center card-subtitle text-muted">Welcome back to your account!</h3>
                <hr>
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
                </div>
                <br>
                <button type="submit" class="btn btn-success">Login</button>
            </form>
          </div>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}{% block title %}signup{% endblock %}
{% block content %} 

<div class="card card-new-shadow my-3 mx-auto rounded">
    <div class="row no-gutters">
      <div class="col-md-5">
        <img src="static/signup.jpg" class="img-fluid rounded-left">
      </div>
      <div class="col-md-6">
        <div class="card-body px-4 mx-auto">
            <form method="POST">
                <h3 class="text-center card-title">Sign Up</h3>
                <h5 class="text-center card-subtitle text-muted">Get started with your SentiVue Account today!</h5>
                <hr>
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" required>
                </div>
                <div class="form-group">
                    <label for="fulltName">Name</label>
                    <input type="text" class="form-control" id="fullName" name="fullName" placeholder="Enter Name" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" required>
                </div>
                <div class="form-group">
                    <label for="passwordConfirm">Confirm Password</label>
                    <input type="password" class="form-control" id="passwordConfirm" name="passwordConfirm" placeholder="Confirm password" required>
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            </div>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/user_home.html
{% extends "base.html" %}{% block title %}Home{% endblock %}
{% block content %}

{% if user.is_authenticated %}
    <div class="my-3">
    <h1>Your Projects</h1>
    <p class="text-muted"><em>Welcome to your profile, {{ user.fullName }}.</em></p>
    <table class="table table-hover">
        <thead class="table-borderless">
            <tr>
                <th scope="col">Project title</th>
            </tr>
        </thead>
        <tbody>
            {% for project in user.projects %}
                <tr>
                    <td>{{ project.title }}</td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="{{ url_for('views.project_view', project_id=project.id) }}" class="btn btn-success btn-sm" role="button">View</a>
                    </td>
                    <td>
                        <button type="button" class="btn btn-danger btn-sm" onClick="deleteProject({{ project.id }})">delete</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{{ url_for('views.project_form') }}" class="btn btn-success">Add Project</a>
    </div>
{% else %}

<div class="my-4">
    <div>
        <h1 class="display-4"><b>Welcome to SentiVue!</b></h1>
        <p class="lead">SentiVue is a robust sentiment analysis tool that assists users in analyzing and summarizing product(s) reviews with its intuitive charts and graphs.</p>
        <img src="static/home.jpg" class="w-50 h-25 mx-auto d-block">
        <hr class="my-4">
        <h3><b>Why SentiVue?</b></h3>
        <p class="text-muted">In today's fast-paced digital landscape, customer feedback is a goldmine of insights, but sifting through countless reviews can be overwhelming. Sentivue empowers you to effortlessly navigate through numerous customer sentiments, ensuring you make data-driven decisions with confidence. </p>
        <p class="text-muted">Utilizing machine learning pedadogies, it categorizes reviews into 'positive', 'negative', and 'neutral'. It also provides users with polarity and subjectivity data to have a further overview of their dataset.</p>
        <p class="text-muted">SentiVue is your go-to tool for text analytics. Join today!</p>
        <a class="btn btn-success btn-lg" href="/sign-up" role="button">Get Started</a>
        <p class="my-2">Already have an account? <a href="/login">Log in</a></p>
    </div>
    </div>
{% endif %}

{% endblock %}


website/templates/view_project.html
<!-- Create a canvas element for the polarity histogram -->
{% extends "base.html" %}{% block title %}Sentiment Analysis{% endblock %}
{% block content %}
    <div class="card card-new-shadow rounded my-2">
    <div class="card-header text-center p-2 bg-dark"></div>
    <div class="card-body p-4">
    <br>
    <div id="result">
    <h1>{{ project.title }}</h1>
    <h5 class="text-muted">{{ project.date }}</h5>
    <div class="border border-start text-left text-lg-start text-dark rounded p-2"><p><b>Project Description:</b><br>{{ project.desc }}</p></div>
    <br>
    {{ output.to_html(classes=["table table-hover table-sm text-right"])| safe }}
    <br>
    <canvas id="polarity-chart" width="360" height="180"></canvas>
    <br>
    <canvas id="sentiment-chart" width="360" height="180"></canvas>
    <br>
    </div>
    <button type="button" class="btn card-link btn-danger" onClick="deleteProject({{ project.id }})">Delete Project</button>
    <button type="button" class="btn card-link btn-success" onClick="window.print()">Export as PDF</button>
    <br>

    <!--ALL REQUIRED JS CODE-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    <script>
        var opData = {{ output.to_json(orient='records')|safe}}
        var sentimentData = {{ output[['Product', 'Sentiment']].to_dict(orient='records')|tojson|safe }};
        var scatterplotData = [];
        var sentimentCounts={};
        var reviewLabel = ['1','2','3','4','5','6','7','8','9','10'];
        opData.forEach(function(row) {
        scatterplotData.push({ x: row.Polarity, y: row.Subjectivity });
        });
        sentimentData.forEach(function (entry) {
        var product = entry['Product'];
        var sentiment = entry['Sentiment'];

        if (!sentimentCounts[product]) {
            sentimentCounts[product] = {};
        }

        if (!sentimentCounts[product][sentiment]) {
            sentimentCounts[product][sentiment] = 0;
        }

        sentimentCounts[product][sentiment]++;
        });

        var productNames = Object.keys(sentimentCounts);
        var positiveCounts = productNames.map(function (product) {
            return sentimentCounts[product]['Positive'] || 0;
        });
        var negativeCounts = productNames.map(function (product) {
            return sentimentCounts[product]['Negative'] || 0;
        });
        var neutralCounts = productNames.map(function (product) {
            return sentimentCounts[product]['Neutral'] || 0;
        });

        function createScatter(chartId, data, labels) {
            var ctx = document.getElementById(chartId).getContext('2d');
            new Chart(ctx, {
                type: 'scatter',
                labels: labels,
                data: {
                    datasets: [{
                        data: data,
                        pointBackgroundColor: 'rgba(0,0,255,1)',
                        pointRadius: 5,
                    }]
                },
                options: {
                    legend: {
                        display: false,
                    },
                    title: {
                        display: true,
                        text: "Polarity vs Subjectivity",
                        fontSize: 20,
                    },
                    scales: {
                    xAxes: [{ticks: {min: -1, max:1}}],
                    yAxes: [{ticks: {min: 0, max:1}}],
                    },
                    tooltips: {
                    callbacks: {
                    label: function(tooltipItem, data) {
                        var label = data.datasets[tooltipItem.datasetIndex].label || '';
                        if (label) {
                        label += ': ';
                        }
                        label += 'Review:' + tooltipItem.index + ', Polarity:' + tooltipItem.xLabel + ', Subjectivity:' + tooltipItem.yLabel;
                        return label; 
                        }}
                    }
                }
            });
        }
        
        var ct = document.getElementById('sentiment-chart').getContext('2d');
        var sentimentChart = new Chart(ct, {
            type: 'bar',
            data: {
                labels: productNames,
                datasets: [
                    {
                        label: 'Positive',
                        data: positiveCounts,
                        backgroundColor: 'green',
                    },
                    {
                        label: 'Negative',
                        data: negativeCounts,
                        backgroundColor: 'red',
                    },
                    {
                        label: 'Neutral',
                        data: neutralCounts,
                        backgroundColor: 'gray',
                    },
                ],
            },
            options: {
                title: {
                    display: true,
                    text: "Sentiment Counts per Product",
                    fontSize: 20,
                },
                scales: {
                    yAxes: [
                    {scaleLabel: {display: true, labelString: "Review Count"}},
                    {ticks: {stepSize: 1}}
                ],
                },
            },
        });
        createScatter('polarity-chart', scatterplotData, reviewLabel);
        //createHistogram('subjectivity-chart', subjectivityData, ReviewLabel, 'Subjectivity')
    </script>
    </div>
    </div>
    </div>
{% endblock %}